#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-POE
Version  : 1.370
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/POE-1.370.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BI/BINGOS/POE-1.370.tar.gz
Summary  : 'Portable, event-loop agnostic eventy networking and multitasking.'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-POE-perl = %{version}-%{release}
Requires: perl(Curses)
Requires: perl(IO::Pipely)
Requires: perl(IO::Tty)
Requires: perl(POE::Test::Loops)
Requires: perl(Term::ReadKey)
BuildRequires : buildreq-cpan
BuildRequires : perl(IO::Pipely)
BuildRequires : perl(IO::Tty)
BuildRequires : perl(POE::Test::Loops)

%description
Version 1.370
--------------------
Detailed Information
--------------------
more information.

%package dev
Summary: dev components for the perl-POE package.
Group: Development
Provides: perl-POE-devel = %{version}-%{release}
Requires: perl-POE = %{version}-%{release}

%description dev
dev components for the perl-POE package.


%package perl
Summary: perl components for the perl-POE package.
Group: Default
Requires: perl-POE = %{version}-%{release}

%description perl
perl components for the perl-POE package.


%prep
%setup -q -n POE-1.370
cd %{_builddir}/POE-1.370

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/POE.3
/usr/share/man/man3/POE::Component.3
/usr/share/man/man3/POE::Component::Client::TCP.3
/usr/share/man/man3/POE::Component::Server::TCP.3
/usr/share/man/man3/POE::Driver.3
/usr/share/man/man3/POE::Driver::SysRW.3
/usr/share/man/man3/POE::Filter.3
/usr/share/man/man3/POE::Filter::Block.3
/usr/share/man/man3/POE::Filter::Grep.3
/usr/share/man/man3/POE::Filter::HTTPD.3
/usr/share/man/man3/POE::Filter::Line.3
/usr/share/man/man3/POE::Filter::Map.3
/usr/share/man/man3/POE::Filter::RecordBlock.3
/usr/share/man/man3/POE::Filter::Reference.3
/usr/share/man/man3/POE::Filter::Stackable.3
/usr/share/man/man3/POE::Filter::Stream.3
/usr/share/man/man3/POE::Kernel.3
/usr/share/man/man3/POE::Loop.3
/usr/share/man/man3/POE::Loop::IO_Poll.3
/usr/share/man/man3/POE::Loop::PerlSignals.3
/usr/share/man/man3/POE::Loop::Select.3
/usr/share/man/man3/POE::NFA.3
/usr/share/man/man3/POE::Pipe.3
/usr/share/man/man3/POE::Pipe::OneWay.3
/usr/share/man/man3/POE::Pipe::TwoWay.3
/usr/share/man/man3/POE::Queue.3
/usr/share/man/man3/POE::Queue::Array.3
/usr/share/man/man3/POE::Resource.3
/usr/share/man/man3/POE::Resource::Aliases.3
/usr/share/man/man3/POE::Resource::Clock.3
/usr/share/man/man3/POE::Resource::Events.3
/usr/share/man/man3/POE::Resource::Extrefs.3
/usr/share/man/man3/POE::Resource::FileHandles.3
/usr/share/man/man3/POE::Resource::SIDs.3
/usr/share/man/man3/POE::Resource::Sessions.3
/usr/share/man/man3/POE::Resource::Signals.3
/usr/share/man/man3/POE::Resources.3
/usr/share/man/man3/POE::Session.3
/usr/share/man/man3/POE::Test::Sequence.3
/usr/share/man/man3/POE::Wheel.3
/usr/share/man/man3/POE::Wheel::Curses.3
/usr/share/man/man3/POE::Wheel::FollowTail.3
/usr/share/man/man3/POE::Wheel::ListenAccept.3
/usr/share/man/man3/POE::Wheel::ReadLine.3
/usr/share/man/man3/POE::Wheel::ReadWrite.3
/usr/share/man/man3/POE::Wheel::Run.3
/usr/share/man/man3/POE::Wheel::SocketFactory.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
